// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AddToChats(arg1:main.PlainMessage):Promise<void>;

export function CoolFunction():Promise<string>;

export function GetChats():Promise<Array<main.Message>>;

export function Greet(arg1:string):Promise<string>;

export function InitValues():Promise<void>;
