// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddToChats(arg1) {
  return window['go']['main']['App']['AddToChats'](arg1);
}

export function CoolFunction() {
  return window['go']['main']['App']['CoolFunction']();
}

export function GetChats() {
  return window['go']['main']['App']['GetChats']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function InitValues() {
  return window['go']['main']['App']['InitValues']();
}
